urls = ["http://www.c-base.org", "http://logbuch.c-base.org/", "http://c-portal.c-base.org",
    "http://c-beam.cbrp3.c-base.org/events", "https://c-beam.cbrp3.c-base.org/c-base-map",
    "http://cbag3.c-base.org/artefact", "https://c-beam.cbrp3.c-base.org/missions", "https://c-beam.cbrp3.c-base.org/weather",
    "http://c-beam.cbrp3.c-base.org/bvg", "http://c-beam.cbrp3.c-base.org/nerdctrl",
    "https://c-beam.cbrp3.c-base.org/rickshaw/examples/fixed.html",
    "https://c-beam.cbrp3.c-base.org/sensors",
    "https://c-beam.cbrp3.c-base.org/ceitloch",
    "http://visibletweets.com/#query=@cbase&animation=2",
    "https://c-beam.cbrp3.c-base.org/reddit",
    "http://vimeo.com/cbase/videos",
    "https://wiki.cbrp3.c-base.org/dokuwiki/",
]
